### ISSUE TITLE
FpgaOverlayManager bucket name is hard coded as 'nih-demos'

### ISSUE THREAD

**Issue by FE-Sobrero** [fpga-open-speech-tools/control_server#6]
Needs to be modified to allow for an additional argument to be passed from the user. This will need to change upstream as well, from user-side passing the input bucket name, adding it to the proxy, and parsing it/passing it from the node server.

![hard-coded-bucket](https://user-images.githubusercontent.com/54909625/97180141-10c42c80-1770-11eb-9206-775554bf155b.png)

**Comment by fe-wickham** [comment]
Closed by #4
